### ISSUE TITLE
[Discussion] Call for maintainers

### ISSUE THREAD

**Issue by brentvatne** [react-native-community/react-native-directory#189]
Want to help manage the repo? We have some open PRs and issues that could use some love! We also want to make this the one-stop source for discovering react-native libraries, so plenty of work to do there! (https://github.com/react-native-community/react-native-directory/issues/188)

**Comment by turnrye** [comment]
Hi @brentvatne, I'm interested in helping out :) Will give it a shot!

**Comment by brentvatne** [comment]
with @turnrye, @jonsamp, @stmoy (+ friends at Microsoft) and me I think we are in a good spot -- but if you'd like to reach out to help please don't hesitate!
